[package]
name = "uwoozy-lang"
version = "0.0.1"
authors = ["Nuxii <nuxii09@gmail.com>"]
edition = "2018"

[[bin]]
name = "uwoozy"
path = "app/main.rs"

[lib]
name = "uwooc"
path = "src/lib.rs"

[dependencies]
