[package]
name = "fluxii-lang"
version = "0.0.1"
authors = ["Nuxii <nuxii09@gmail.com>"]
edition = "2018"

[[bin]]
name = "fluxii"
path = "app/main.rs"

[lib]
name = "fluxc"
path = "src/lib.rs"

[dependencies]