[package]
name = "libcosyc_diagnostics"
version = "0.1.0"
authors = ["NuxiiGit <nuxii09@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
