[package]
name = "libcosyc_parse"
version = "0.1.0"
authors = ["NuxiiGit <nuxii09@gmail.com>"]
edition = "2018"

[dependencies]
libcosyc_scan = { path = "../libcosyc_scan" }
libcosyc_diagnostic = { path = "../libcosyc_diagnostic" }
