[package]
name = "cosyc"
version = "0.0.1"
authors = ["NuxiiGit"]
edition = "2018"

[dependencies]
libcosyc_parser = { path = "../libcosyc_parser" }
libcosyc_diagnostics = { path = "../libcosyc_diagnostics" }