[package]
name = "libcosyc_parser"
version = "0.0.1"
authors = ["NuxiiGit"]
edition = "2018"

[dependencies]
libcosyc_syntax = { path = "../libcosyc_syntax" }
libcosyc_diagnostics = { path = "../libcosyc_diagnostics" }
libcosyc_lexer = { path = "../libcosyc_lexer" }